spring:
  datasource:
    url: jdbc:mariadb://10.0.4.32:3306/dijer
    username: dijer119
    password: Djswpsk1!!!
    driver: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
